# -*- coding: utf-8 -*-
"""Copia_de_myAppInmoT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17vB7DNnAUk2A-EgtysG7BzYpcUbmCClt

# Pipes - Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Aplicar tubería
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Función para eliminar atípicos (similar a la profesora)
def limpiar_atipicos(X):
    """
    Limpia valores atípicos reemplazándolos con np.nan
    """
    # Limpiar LotFrontage (valores >= 270)
    X.loc[X["LotFrontage"] >= 270, "LotFrontage"] = np.nan

    # Limpiar TotalBsmtSF (valores > 5500)
    X.loc[X["TotalBsmtSF"] > 5500, "TotalBsmtSF"] = np.nan

    # Limpiar BsmtFinSF1 (valores > 5500)
    X.loc[X["BsmtFinSF1"] > 5500, "BsmtFinSF1"] = np.nan

    return X

print('Función de limpieza de atípicos definida')

import pickle
with open('pipeline_final.pkl', 'rb') as f:
    pipeline_final = pickle.load(f)

pipeline_final

#Cargamos los datos futuros
data = pd.read_csv("/content/datos_futuro_vivienda.csv")
data.head()

import streamlit as st
import pandas as pd

st.set_page_config(page_title="Predicción de precio de una casa", layout="wide")
st.title('Predicción de precio de una casa')

# Opciones para los campos importantes:
MSZoning_opts = ['RL', 'RM', 'C (all)', 'FV', 'RH']
Neighborhood_opts = [
    'CollgCr', 'Veenker', 'Crawfor', 'NoRidge', 'Mitchel', 'Somerst', 'NWAmes', 'OldTown',
    'BrkSide', 'Sawyer', 'NridgHt', 'NAmes', 'SawyerW', 'IDOTRR', 'MeadowV', 'Edwards',
    'Timber', 'Gilbert', 'StoneBr', 'ClearCr', 'NPkVill', 'Blmngtn', 'BrDale', 'SWISU', 'Northridge'
]

# SOLO ESTOS 7 campos visibles para el usuario:
entrada = {
    'MSZoning': st.selectbox('Clasificación de zona (MSZoning)', MSZoning_opts, index=0),
    'Neighborhood': st.selectbox('Barrio (Neighborhood)', Neighborhood_opts, index=0),
    'GrLivArea': st.number_input('Área habitable en pies cuadrados (GrLivArea)', min_value=200, max_value=7000, value=1500),
    'LotArea': st.number_input('Área del lote (LotArea)', min_value=1000, max_value=100000, value=8450),
    'OverallQual': st.slider('Calidad general (OverallQual)', min_value=1, max_value=10, value=6),
    'FullBath': st.slider('Baños completos (FullBath)', min_value=0, max_value=3, value=1),
    'BedroomAbvGr': st.slider('Habitaciones (BedroomAbvGr)', min_value=0, max_value=8, value=3),
}

# RELLENA EL RESTO de variables del pipeline con defaults (usualmente, los valores más frecuentes del dataset de entrenamiento)
entrada_defaults = {
    'MSSubClass': 20,
    'LotFrontage': 60,
    'Street': 'Pave',
    'Alley': 'NA',
    'LotShape': 'Reg',
    'LandContour': 'Lvl',
    'Utilities': 'AllPub',
    'LotConfig': 'Inside',
    'LandSlope': 'Gtl',
    'Condition1': 'Norm',
    'Condition2': 'Norm',
    'BldgType': '1Fam',
    'HouseStyle': '1Story',
    'OverallCond': 5,
    'RoofStyle': 'Gable',
    'RoofMatl': 'CompShg',
    'Exterior1st': 'VinylSd',
    'Exterior2nd': 'VinylSd',
    'MasVnrType': 'None',
    'MasVnrArea': 0,
    'ExterQual': 'TA',
    'ExterCond': 'TA',
    'Foundation': 'PConc',
    'BsmtQual': 'TA',
    'BsmtCond': 'TA',
    'BsmtExposure': 'No',
    'BsmtFinType1': 'Unf',
    'BsmtFinSF1': 0,
    'BsmtFinType2': 'Unf',
    'BsmtFinSF2': 0,
    'BsmtUnfSF': 0,
    'TotalBsmtSF': 0,
    'Heating': 'GasA',
    'HeatingQC': 'Ex',
    'CentralAir': 'Y',
    'Electrical': 'SBrkr',
    '1stFlrSF': 0,
    '2ndFlrSF': 0,
    'LowQualFinSF': 0,
    'BsmtFullBath': 0,
    'BsmtHalfBath': 0,
    'HalfBath': 0,
    'KitchenAbvGr': 1,
    'KitchenQual': 'TA',
    'TotRmsAbvGrd': 6,
    'Functional': 'Typ',
    'Fireplaces': 0,
    'FireplaceQu': 'NA',
    'GarageType': 'Attchd',
    'GarageYrBlt': 2000,
    'GarageFinish': 'Unf',
    'GarageCars': 1,
    'GarageArea': 200,
    'GarageQual': 'TA',
    'GarageCond': 'TA',
    'PavedDrive': 'Y',
    'WoodDeckSF': 0,
    'OpenPorchSF': 0,
    'EnclosedPorch': 0,
    '3SsnPorch': 0,
    'ScreenPorch': 0,
    'PoolArea': 0,
    'PoolQC': 'NA',
    'Fence': 'NA',
    'MiscFeature': 'NA',
    'MiscVal': 0,
    'MoSold': 6,
    'YrSold': 2010,
    'SaleType': 'WD',
    'SaleCondition': 'Normal',
    'YearBuilt_Category': '1981-2010',
    'YearRemodAdd_Category': '1981-2010',
}

# Combina los campos pedidos con los defaults (lo del usuario prevalece)
for k,v in entrada_defaults.items():
    if k not in entrada:
        entrada[k] = v

data = pd.DataFrame([entrada])

if st.button('Predecir precio'):
    pred = pipeline_final.predict(data)
    st.success(f"El precio estimado de la casa es: ${pred[0]:,.2f}")
    st.write("Datos ingresados:")
    st.dataframe(data)

#Hacemos la predicción con el Tree
Y_rf = pipeline_final.predict(data)
print(Y_rf)

data['Prediccion']=Y_rf
data